<a href="https://colab.research.google.com/github/seodalzzz/ESAA/blob/Exercises/100_Numpy_exercises_34~66.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [1]:
%run initialise.py

ERROR:root:File `'initialise.py'` not found.


In [3]:
import numpy as np

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [ ]:
print(np.arange('2016-07','2016-08',dtype='datetime64[D]'))

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [ ]:
A=np.array(np.random.random())
B=np.array(np.random.random())
print(A,B)

np.add(A,B,out=B)
np.divide(A,2,out=A)
np.multiply(A,(-1),out=A)
np.multiply(A,B,out=A)
print(A)


0.6290429884584459 0.7909984393975759
-0.4466335517566752


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [ ]:
array1=np.random.random(5)*10
print(array1)

result1=array1.astype(int)
print(result1)
result2=array1-(array1%1)
print(result2)
result3=np.floor(array1)
print(result3)
result4=np.ceil(array1)-1
print(result4)

[7.99301278 6.91231166 6.8442525  8.44391309 3.27570425]
[7 6 6 8 3]
[7. 6. 6. 8. 3.]
[7. 6. 6. 8. 3.]
[7. 6. 6. 8. 3.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [ ]:
mat1=np.zeros((5,5))
mat1+=np.arange(0,5)
print(mat1)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [ ]:
def generate():
  for x in range(10):
    yield x
array2=np.fromiter(generate(),dtype=float)
print(array2)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [ ]:
array3=np.linspace(0,1,11,endpoint=False)
print(array3)

[0.         0.09090909 0.18181818 0.27272727 0.36363636 0.45454545
 0.54545455 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [ ]:
array4=np.random.random(10)
array5=np.sort(array4)
print(array5)

[0.0426722  0.13010173 0.32003033 0.47503498 0.70062058 0.73467367
 0.77517094 0.91570782 0.93760447 0.94095178]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [ ]:
array6=np.arange(5)
array7=np.add.reduce(array6)
print(array7)

10


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [ ]:
array8=np.random.random(10)
array9=np.random.random(10)

print((array8==array9).min())

False


#### 43. Make an array immutable (read-only) (★★☆)

In [ ]:
array10=np.arange(10)
array10.flags.writeable=False
#array10[5]=6

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [ ]:
array11=np.random.random((10,2))
x=array11[0:10,0]
y=array11[0:10,1]

r=np.sqrt(x*x+y*y)
p=np.arctan2(y,x)

print(r)
print(p)

[1.08433423 0.59386377 1.23537812 0.57887475 0.6339177  0.64861868
 0.15593998 0.60047523 0.5715095  0.36616652]
[0.54304411 0.96572015 0.77381926 0.06657256 0.47716342 1.25473184
 0.74716884 0.44715433 0.46716427 0.53754644]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [ ]:
array12=np.random.random(10)
print(array12)
array12[array12.max()==array12]=0
print(array12)

[0.22112272 0.68264112 0.6967118  0.41329909 0.9429795  0.41520887
 0.19100837 0.60446433 0.85384076 0.69278173]
[0.22112272 0.68264112 0.6967118  0.41329909 0.         0.41520887
 0.19100837 0.60446433 0.85384076 0.69278173]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [ ]:
mat2=np.zeros((5,5),[('x',float),('y',float)])
mat2['x'],mat2['y']=np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))

print(mat2)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [ ]:
x=np.random.random(5)
y=np.random.random(5)
mat3=np.zeros((5,5))
mat4=1.0/np.subtract.outer(x,y)

for i in range(len(x)):
  for j in range(len(y)):
      mat3[i,j]=(1/(x[i]-y[j]))

print(mat3)
print(mat4)

[[  1.37565859   3.19269739   1.33493559   2.83596405   5.55580782]
 [  2.4944368  -78.01727289   2.36368979  37.62039395  -6.8474098 ]
 [  3.30172084  -9.02222479   3.07647223 -13.99807281  -4.09734712]
 [  1.23764308   2.53628396   1.20458322   2.3058656    3.83061527]
 [-47.60942352  -2.30036291 853.95804885  -2.52962817  -1.76075878]]
[[  1.37565859   3.19269739   1.33493559   2.83596405   5.55580782]
 [  2.4944368  -78.01727289   2.36368979  37.62039395  -6.8474098 ]
 [  3.30172084  -9.02222479   3.07647223 -13.99807281  -4.09734712]
 [  1.23764308   2.53628396   1.20458322   2.3058656    3.83061527]
 [-47.60942352  -2.30036291 853.95804885  -2.52962817  -1.76075878]]


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [4]:
for dtype in [np.int8, np.int32, np.int64]:
  print(np.iinfo(dtype).min)
  print(np.iinfo(dtype).max)

for dtype in [np.float32, np.float]:
  print(np.finfo(dtype).min)
  print(np.finfo(dtype).max)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
-1.7976931348623157e+308
1.7976931348623157e+308


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """


#### 49. How to print all the values of an array? (★★☆)

In [12]:
array14=np.zeros((32,32))
np.set_printoptions(threshold=float("inf"))
print(array14)




[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [30]:
num=5.2
array15=np.random.randint(0,10,10)
print(array15)

array16=np.abs(array15-num)
print(array16)
  #argmin()은 index를 return
print(array15[array16.argmin()])

[5 2 9 5 7 4 4 8 8 8]
[0.2 3.2 3.8 0.2 1.8 1.2 1.2 2.8 2.8 2.8]
5


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [34]:
position=('position',[('x',float,1),('y',float,1)])
color=('colot',[('r',float),('g',float),('b',float)])
data=np.zeros(10,[position,color])

print(data)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  This is separate from the ipykernel package so we can avoid doing imports until


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [39]:
array17=np.random.random((10,2))
x,y=np.atleast_2d(array17[:,0],array17[:,1])
dis=np.sqrt((x-x.T)**2+(y-y.T)**2)
print(dis)

[[0.         0.21022505 0.80310461 0.06881978 0.84801775 0.53342145
  0.43724247 0.77695968 0.61427813 0.44768664]
 [0.21022505 0.         0.71244832 0.26423081 0.73673555 0.32486265
  0.37014647 0.56851921 0.40924455 0.25824845]
 [0.80310461 0.71244832 0.         0.79254679 0.09328759 0.736051
  0.36586707 0.68167754 0.80633861 0.82322487]
 [0.06881978 0.26423081 0.79254679 0.         0.84410914 0.58906548
  0.42892601 0.82273334 0.67278905 0.51099959]
 [0.84801775 0.73673555 0.09328759 0.84410914 0.         0.71862389
  0.41546971 0.63055839 0.78100868 0.81870774]
 [0.53342145 0.32486265 0.736051   0.58906548 0.71862389 0.
  0.51570331 0.27830104 0.09374574 0.14280822]
 [0.43724247 0.37014647 0.36586707 0.42892601 0.41546971 0.51570331
  0.         0.60804998 0.60622601 0.54910977]
 [0.77695968 0.56851921 0.68167754 0.82273334 0.63055839 0.27830104
  0.60804998 0.         0.25885729 0.41931564]
 [0.61427813 0.40924455 0.80633861 0.67278905 0.78100868 0.09374574
  0.60622601 0.2588572

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [50]:
array18=np.random.random(10)*10
print(array18)
array19=array18.astype(np.int64,copy=False)
print(array19)

[2.01832929 8.08086936 8.05610893 2.12477917 5.24660209 1.66047133
 6.16578168 5.56489173 5.08072256 1.64994922]
[2 8 8 2 5 1 6 5 5 1]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [49]:
from io import StringIO
string1=StringIO("""1, 2, 3, 4, 5\n
6,  ,  , 7, 8\n
 ,  , 9,10,11\n""")
array20=np.genfromtxt(string1,delimiter=",",dtype=np.int)
print(array20)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [52]:
array21=np.arange(25).reshape(5,5)
print(array21)

for index, value in np.ndenumerate(array21):
  print(index,value)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
(0, 0) 0
(0, 1) 1
(0, 2) 2
(0, 3) 3
(0, 4) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8
(1, 4) 9
(2, 0) 10
(2, 1) 11
(2, 2) 12
(2, 3) 13
(2, 4) 14
(3, 0) 15
(3, 1) 16
(3, 2) 17
(3, 3) 18
(3, 4) 19
(4, 0) 20
(4, 1) 21
(4, 2) 22
(4, 3) 23
(4, 4) 24


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [54]:
x,y=np.meshgrid(np.linspace(-1,1,10),np.linspace(-1,1,10))
d=np.sqrt(x*x+y*y)
sigma,mu=1.0,0.0
G=np.exp(-((d-mu)**2)/(2*sigma**2))

print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [55]:
n=10
p=5
array22=np.zeros((n,n))
np.put(array22,np.random.choice(range(n*n),p,replace=False),1)
print(array22)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 1. 1. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [66]:
array23=np.random.randint(0,10,100).reshape(10,10)
print(array23)
array24=array23-array23.mean(axis=1,keepdims=True)
print(array24)

[[8 3 3 2 4 6 3 9 3 8]
 [0 2 6 7 5 7 6 7 7 2]
 [9 3 9 6 1 7 4 7 8 5]
 [1 3 6 9 6 0 8 5 0 4]
 [8 4 7 9 8 6 8 3 8 0]
 [0 5 9 0 3 1 0 1 1 1]
 [9 4 7 3 6 5 2 3 0 9]
 [7 3 6 1 4 0 1 7 4 2]
 [1 7 8 4 0 7 3 2 2 9]
 [2 4 7 3 0 6 7 6 3 0]]
[[ 3.1 -1.9 -1.9 -2.9 -0.9  1.1 -1.9  4.1 -1.9  3.1]
 [-4.9 -2.9  1.1  2.1  0.1  2.1  1.1  2.1  2.1 -2.9]
 [ 3.1 -2.9  3.1  0.1 -4.9  1.1 -1.9  1.1  2.1 -0.9]
 [-3.2 -1.2  1.8  4.8  1.8 -4.2  3.8  0.8 -4.2 -0.2]
 [ 1.9 -2.1  0.9  2.9  1.9 -0.1  1.9 -3.1  1.9 -6.1]
 [-2.1  2.9  6.9 -2.1  0.9 -1.1 -2.1 -1.1 -1.1 -1.1]
 [ 4.2 -0.8  2.2 -1.8  1.2  0.2 -2.8 -1.8 -4.8  4.2]
 [ 3.5 -0.5  2.5 -2.5  0.5 -3.5 -2.5  3.5  0.5 -1.5]
 [-3.3  2.7  3.7 -0.3 -4.3  2.7 -1.3 -2.3 -2.3  4.7]
 [-1.8  0.2  3.2 -0.8 -3.8  2.2  3.2  2.2 -0.8 -3.8]]


#### 59. How to sort an array by the nth column? (★★☆)

In [70]:
array25=np.random.randint(0,10,100).reshape(10,10)
print(array25)
print("\n")
print(array25[array25[:,1].argsort()])

[[2 2 3 1 2 7 3 8 5 0]
 [1 5 6 0 1 4 7 3 5 4]
 [8 3 4 1 5 4 2 6 1 1]
 [2 7 2 1 7 6 3 8 7 8]
 [1 6 7 6 2 5 8 6 7 7]
 [3 6 5 6 3 9 1 5 7 6]
 [5 2 2 9 4 8 9 7 9 8]
 [5 9 8 0 5 2 2 5 8 0]
 [9 9 2 4 8 5 7 5 0 3]
 [6 9 9 2 7 1 4 5 9 3]]


[[2 2 3 1 2 7 3 8 5 0]
 [5 2 2 9 4 8 9 7 9 8]
 [8 3 4 1 5 4 2 6 1 1]
 [1 5 6 0 1 4 7 3 5 4]
 [1 6 7 6 2 5 8 6 7 7]
 [3 6 5 6 3 9 1 5 7 6]
 [2 7 2 1 7 6 3 8 7 8]
 [5 9 8 0 5 2 2 5 8 0]
 [9 9 2 4 8 5 7 5 0 3]
 [6 9 9 2 7 1 4 5 9 3]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [72]:
array26=np.random.randint(0,10,100).reshape(10,10)
print(array26)

print((~array26.any(axis=0)).any())

[[7 5 3 9 1 9 1 7 4 9]
 [6 2 2 1 1 7 4 3 2 9]
 [8 3 8 3 2 9 8 5 0 0]
 [5 4 0 4 5 2 5 0 4 5]
 [3 0 0 5 3 8 4 0 5 9]
 [8 3 9 3 7 0 7 0 1 1]
 [7 4 3 7 0 2 7 6 3 3]
 [0 3 7 3 1 3 1 1 9 7]
 [6 2 9 0 4 7 6 4 0 2]
 [0 1 0 0 6 9 3 8 6 7]]
False


#### 61. Find the nearest value from a given value in an array (★★☆)

In [76]:
num=0.52
array27=np.random.random(10)
print(array27)

array28=np.abs(array27-num)
print(array28)
  #argmin()은 index를 return
print(array27[array28.argmin()])

[0.34269172 0.17884377 0.35412941 0.54080808 0.230045   0.75054511
 0.41213608 0.86385434 0.35902548 0.36323721]
[0.17730828 0.34115623 0.16587059 0.02080808 0.289955   0.23054511
 0.10786392 0.34385434 0.16097452 0.15676279]
0.5408080798240066


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [81]:
array29=np.arange(3).reshape(1,3)
array30=np.arange(3).reshape(3,1)
print(array29,array30)

iter=np.nditer([array29,array30,None])

for x,y,z in iter:
  z[...]=x+y

print(iter.operands[2])

[[0 1 2]] [[0]
 [1]
 [2]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [83]:
class NameArray(np.ndarray):
  def __new__(cls,array,name="no name"):
    obj=np.asarray(array).view(cls)
    obj.name=name
    return obj
  def __array_finalize__(self,obj):
    if obj is None:
      return
    self.info=getattr(obj,'name','no name')
data=NameArray(np.arange(10),'range_10')
print(data.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [87]:
array31=np.zeros(10)
array32=np.random.randint(0,len(array31),20)
np.add.at(array31,array32,1)
print(array32)
print(array31)

[8 9 1 0 0 5 2 3 3 6 1 7 4 5 0 7 4 5 3 2]
[3. 2. 2. 3. 2. 3. 1. 2. 1. 1.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [92]:
array33=[1,2,3,4,5,6]
array34=[1,5,6,4,2,3]
array35=np.bincount(array34,array33)
print(array35)


[0. 1. 5. 6. 4. 2. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [95]:
w,h=16,16
I=np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F=I[...,0]*(256*256)+I[...,1]*256+I[...,2]
n=len(np.unique(F))
print(n)
print(np.unique(I))

8
[0 1]
