<a href="https://colab.research.google.com/github/seodalzzz/ESAA/blob/main/Python_Machine_Learning_CHAP1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#__CHAP1 파이썬 기반의 머신러닝과 생태계 이해__

## __1. 머신러닝의 개념__

머신러닝(Machine Learning) : 애플리케이션을 수행하지 않고도 데이터를 기반으로 패턴을 학습하고 결과를 예측하는 알고리즘 기법

머신러닝은 데이터를 기반으로 숨겨진 패턴을 인지해 여러 문제를 해결한다. 머신러닝 알고리즘은 데이터를 기반으로 통계적인 신뢰도를 강화하고 예측 오류를 최소화하기 위한 다양한 수학적 기법을 적용해 데이터 내의 패턴을 스스로 인지뢰고 신뢰도 있는 예측 결과를 도출해 낸다.


###1) 머신러닝의 분류

지도학습/비지도학습/강화학습

* 지도학습 : 분류, 회귀, 추천시스템, 시각/음성감지/인지, 텍스트분석, NLP
* 비지도학습 : 클러스터링, 차원 축소, 강화학습

###2) 데이터 전쟁
머신러닝은 데이터에 매우 의존적임. 따라서 좋은 품직의 데이터를 갖추지 못한다면 머신런이의 수행 결과도 좋을 수 없음.

데이터를 이해하고 효율적으로 가공, 처리, 추출해 최적의 데이터를 기반으로 알고리즘을 구동할 수 있도록 준비하는 능력이 중요함.


###3) 파이썬과 R 기반의 머신러닝 비교

머신러닝 프로그램을 작성할 수 있는 대표적인 오픈 소스 프로그램 언어

  * R
   * 통계 전용 언어
   * 오랜 기간동안 많은 R 사용자들이 생성하고 검증해온 다양하고 많은 통계 패키지 보유

  *(2) Python
    * 쉽고 뛰어난 개발 생산성으로 전 세계 개발자들이 파이썬을 선호함
    * 오픈 소스 계열의 전폭적인 지지를 받고 있으며 많은 라이브러리로 인해 개발 시 높은 생산성을 보장해 줌
    * 인터프리터 언어(Interpreter Language)의 특성 상 속도는 느리지만, 뛰어난 확장성, 유연성, 호환성으로 인해 서버, 네트워크, 시스템, IOT, 데스크톱까지 다양한 영역에서 사용되고 있음
    * 머신러닝 애플리케이션과 결합한 다양한 애플리케이션 개발이 가능함
    * 엔터프라이즈 아키미처로의 확장 및 마이크로서비스 기반의 실시간 연계 등 다양한 기업 환경으로의 확산이 가능함
    * __딥러닝 프레임워크인 텐서플로, 케라스, 파이토치 등에서 파이썬 우선 전책으로 파이썬을 지원하고 있음__





##__2. 파이썬 머신러닝 생태계를 구성하는 주요 패키지__
  * 머신러닝 패키지 : __사이킷런(Scikit-Learn)__, 텐서플로, 케라스
  * 행렬/선형대수/통계 패키지 : __넘파이(Numpy)__
    + 사이킷런을 비롯한 많은 머신러닝 패키지가 넘파이 기반으로되 되어 있음
  * 데이터 핸들링 : __판다스__
    + 대표적인 데이터 처리 패키지
    + 2차원 데이터 처리에 특화되어 있음
  * 시각화 : __맷플롯립__, 시본
    + 시본을 사용하기 위해서는 맷플롯립을 어느정도 알고 있어야 함
    
  * 주피터 노트북 : 대표적인 아이파이썬(대화형 파이썬 툴) 지원 툴
    + 중요 코드 단위로 설명ㅇ르 적고 코드를 수행해 그 결과를 볼수 있게 만들어 직관적으로 어떤 코드가 어떤 역할을 하는지 매우 쉽게 이해할 수 있도록 지원함
  




###1) 파이썬 머신러닝을 위한 S/W 설치
  * Anaconda 설치 - https://www.anaconda.com/download/
  * 주피터 노트북 접속
  * 넘파이, 판다스, 맷플롯립, 시본, 사이킷런 모듈 임포트 및 오류 발생 확인 (설치 확인)
  * Micro Soft visual studio build toos 2015 이상 버전 설치

 

* 머신러닝 애플리케이션을 파이썬으로 개발한다면 대부분의 코드는 사이킷런의 머신러닝 알고리즘에 입력하기 위한 데이터의 추출/가공/변형, 원하는 차원 배열로의 변환을 포함해 머신러닝 알고리즘 처리 결과에 대한 다양한 가공 등으로 구성되며 이 같은 데이터 처리 부분은 넘파이와 판다스의 몫
* 사이킷런이 넘파이 기반에서 작성됐기 때문에 넘파이읭 기본 프레임 워크를 이해하는 것이 중요

##__3. 넘파이__
 머신러닝의 주요 알고리즘은 선형대수와 통계 등에 기반함.

 Numpy(Numerical Python)는 파이썬에서 선형대수 기반의 프로그램을 쉽게 만들 수 있도록 지원하는 대표적인 패키지

 루프를 사용하징 않고 대량 데이터의 배열 연산을 가능하게 함. >> 빠른 배열 연산 속도

 C/C++과 같은 저수준 언어 기반의 호환 API를 제공함으로 수행 성능이 중요한 부분은 C/C++ 기반의 코드로 작성하고, 이를 넘파이에서 호출하는 방식으로 쉽게 통합 가능

 다양한 데이터 핸들링 기능을 제공하지만 2차원 형태의 행렬 데이터에 대한 다양한 가공과 변환, 여러 통계용 함수의 적용 등에서 판다스의 편리성에는 미치지 못함

__많은 머신러닝 알고리즘이 넘파이 기반으로 작성돼 있고, 이들 알고리즘의 입력 데이터와 출력 데이터를 넘파이 배열 타입으로 사용하기때문에 넘파이를 이해하는 것은 파이썬 기반의 머신러닝에서 매우 중요함.__





###1) 넘파이 ndarry 개요


In [2]:
# 넘파이 모듈 임포트

import numpy as np

> import numpy만 해도 충분하지만, as np를 추가하여 약어로 모듈을 표현해주는 것이 관례임




* ndarry
  + 넘파이의 기반 데이터 타입
  + ndarry를 이용해 넘파이에서 다차원 배열을 쉽게 생성하고 다양한 연산을 수행할 수 있음




+ array() : 파이썬의 리스트와 같은 다양한 인자를 입력받아서 ndarray로 변환
  + 생성된 ndarray 배열의 shape 변수는 ndarray의 크기, 즉 행과 열의 수를 튜플 평태로 가지고 있으며 이를 통해 ndarray 배열의 차원까지 알 수 있음
  + array() 함수의 인자로는 파이썬의 리스트 객체가 주로 사용됨. 리스는 []는 1차원이고, [[]]는 2차원과 같은 형태로 배열의 차원과 크기를 쉽게 표현할 수 있기 때문








In [ ]:
# aray() 함수

array1=np.array([1,2,3]) #1차원 array로 3개의 데이터를 가지고 있음
print('array1 type : ',type(array1))
print('array1 array 형태 :',array1.shape)

array2=np.array([[1,2,3],[2,3,4]])
print('array2 type : ', type(array2))
print('arry2 형태 : ',array2.shape)

array3=np.array([[1,2,3]]) #1개의 row와 3개의 col으로 구성된 2차원 데이터
print('array3 type : ', type(array3))
print('array3 형태 : ', array3.shape)


array1 type :  <class 'numpy.ndarray'>
array1 array 형태 : (3,)
array2 type :  <class 'numpy.ndarray'>
arry2 형태 :  (2, 3)
array3 type :  <class 'numpy.ndarray'>
array3 형태 :  (1, 3)





> array1.shape // (3,) : 1차원 array로 3개의 데이터를 가지고 있음

> array3.shape // (1,3) : 1개의 row, 3개의 col을 가진 2차원 데이터






In [ ]:
# 각 array의 차원을 ndarray.ndim을 이용해 확인

print('array1 : {:0}차원, array2 : {:1}차원, array3 : {:2}차원'.format(array1.ndim,array2.ndim,array3.ndim))

array1 : 1차원, array2 : 2차원, array3 :  2차원




> array1은 1차원, array3은 2차원




###2) ndarray의 데이터 타입

  + ndarray내의 데이터 값은 숫자 값, 문자열 값, bool 값 등이 모두 가능함
  + 숫자형의 경우 int 형, unsigned int 형, float 형, complex 타입 제공
  + ndarray내의 데이터 타입은 같은 데이터 타입만 가능함
    + 만약 다른 데이터 유형이 섞여 있는 리스트를 ndarray로 변경하면 데이터 크기가 더 큰 데이터 타입으로 형 변환을 일괄 적용함



In [ ]:
# dtype 속성으로 ndarray 내의 데이터 타입 확인하기
list1=[1,2,3]
print(type(list1))
array1=np.array(list1)
print(type(array1))
print(array1,array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64




> list1을 array()함수를 이용하여 ndarray로 변환
> 변경된 ndarray내의 데이터 값은 모두 int32형




In [ ]:
#int형과 string형이 섞여 있는 리스트를 ndarray로 변경
list2=[1,2,'test']
array2=np.array(list2)
print(array2, array2.dtype)

#int형과 float형이 섞여 있는 리스트를 ndarray로 변경
list3=[1,2,3.0]
array3=np.array(list3)
print(array3,array3.dtype)


['1' '2' 'test'] <U21
[1. 2. 3.] float64




> int 형 값과 문자열이 섞여 있는 list2를 ndarray로 변환하면 숫자형 값 1,2,가 모두 문자열 '1','2'로 바뀜
> int 형과 float형이 섞인 list3의 경우도 int 1,2가 모두 1,2 인 float 형으로 바뀜




* astype() : ndarray 내 데이터 값의 타입 변경 
  + astype()에 인자로 원하는 타입을 문자열로 지정
  + 대용량 데이터의 ndarray를 만들 때 많은 메모리가 사용되는데, 메모리를 절약해야 할 때 사용 (ex. int 형으로 충분한 경우인데 float형이 사용되고 있는 경우)


In [ ]:
# int32형 데이터를 float64로 변환
array_int=np.array([1,2,3])
array_float=array_int.astype('float64')
print(array_float,array_float.dtype)

#float64형 ndarray를 다시 int32형으로 변경
array_int1=array_float.astype('int32')
print(array_int1,array_int1.dtype)

array_float1=np.array([1.1,2.1,3.1])
array_int2=array_float1.astype('int32')
print(array_int2,array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


> float형을 int형으로 변환 할 때 소수점 이하의 자리는 모두 없어짐


###3) ndarray를 편리하게 생성하기 - arange, zeros, ones
  * 특정 크기와 차원을 가진 ndarray를 연속값이나 0 또는 1로 초기화해 생성해야 할 경우 사용
  * 테스트용 데이터를 만들거나 대규모의 데이터를 일괄적으로 초기화해야 할 경우에 사용

  * arange() : 0부터 함수인자 값 -1까지의 값을 순차적으로 ndarray의 데이터값으로 변환
    + default 함수 인자 값은 stop 값이며 0부터 stop 값에 -1을 더한 값까지의 연속 숫자 값으로 구성된 1차원 array를 만듦
    + range와 유사하게 start값도 부여해 0이 아닌 다른 값부터 시작한 연속 값을 부여할수도 있음

  * zeros() : 함수 인자로 튜플 형태의 shape값을 입력하면 모든 값을 0으로 채운 해당 shape를 가진 ndarray를 반환
    + 함수인자로 dtype을 정해주지 않으면 default로 float64 형의 데이터로 ndarray를 채움

  * ones() : 함수인자로 튜플 형태의 shape 값을 입력하면 모든 값을 1로 채운 해당 shape를 가진 ndarray를 반환
    + 함수인자로 dtype을 정해주지 않으면 default로 float64 형의 데이터로 ndarray를 채움

    


In [9]:
#arange()
sequence_array=np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

#zeros()
zero_array=np.zeros((3,2),dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array)
  
#ones()
one_array=np.ones((3,2))
print(one_array)
print(one_array.dtype,one_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)
[[0 0]
 [0 0]
 [0 0]]
int32 [[0 0]
 [0 0]
 [0 0]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


###4) ndarray의 차원과 크기를 변경하는 reshape()

  * reshape() : ndarray를 특정 차원 및 크기로 변환
    * 변환을 원하는 크기를 함수 인자로 부여
    * 지정된 사이즈로 변경이 불가능하면 오류 발생
    * 인자로 -1을 사용할 경우 원래 ndarray와 호환되는 새로운 shape로 변환

In [10]:
#reshape()
array1=np.arange(10)
print('array1:\n',array1)

array2=array1.reshape(2,5)
print('array2:\n',array2)

array3=array1.reshape(5,2)
print('array3:\n',array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]




> arrya1을 (4,3) 형태로 reshape하려 하면 오류 발생



In [13]:
#reshape 인자로 -1 사용
array1=np.arange(10)
print(array1)
array2=array1.reshape(-1,5)
print('array2 shape:',array2.shape)
array3=array1.reshape(5,-1)
print('array3.shape:',array3.shape)


[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3.shape: (5, 2)


In [14]:
#호환되지 않는 형태로는 변환 불가
array1=np.arange(10)
array4=array1.reshaep(-1,4)

AttributeError: ignored

In [15]:
#reshape(-1,1)
array1=np.arange(8)
array3d=array1.reshape((2,2,2))
print('array3d:\n',array3d.tolist())

#3차원 ndarray를 2차원 ndarray로 변환
array5=array3d.reshape(-1,1)
print('array5:\n', array5.tolist())
print('array5 shape:',array5.shape)

#1차원 ndarray를 2차원 ndarray로 변환
array6=array1.reshape(-1,1)
print('array6:\n',array6.tolist())
print('array6 shape:\n',array6.shape)

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape:
 (8, 1)


> -1인자는 reshape(-1,1)과 같은 형태로 자주사용됨. reshape(-1,1)은 원본 ndarray가 어떤 형태라도 2차원이고, 여러개의 로우를 가지되 반드시 1개의 칼럼을 가진 ndarray로 변환됨을 보장

> 여러 개의 넘파이 adarray는 stack이나 concat으로 결합할 때 각각의 ndarray 형태를 통일해 유용하게 사용됨

###5) 넘파이의 ndarray의 데이터 세트 선택하기 - 인덱싱(Indexing)
  * 넘파이에서 ndarray 내의 일부 데이터 세트나 특정 데이터만을 선택
  * 특정한 데이터만 추출 : 원하는 위치의 인덱스 값을 지정하면 해당 위치의 데이터가 반환
  * 슬라이싱(Slicing) : 연속된 인덱스상의 ndarray를 추출
    * :기호 사이에 시작 인덱스와 종료 인덱스를 표시하면 시작 인덱스에서 종료 인덱스 -1 위치에 있는 데이터의 ndarray를 반환
  * 팬시 인덱싱(Fancy Indexing) : 일정한 인덱싱 집합을 리스트 또는 ndarray 형태로 지정해 해당 위치에 있는 데이터의 ndarray를 반환
  * 불린 인덱싱 (Boolean Indexing) : 특정 조건에 해당하는지 여부인 True/False 값 인덱싱 집합을 기반으로 True에 해당하는 인덱스 위치에 있는 데이터의 ndarray를 반환



####(1) 단일 값 추출
  * 1개의 데이터값을 선택하려면 ndarray 객체에 해당하는 위치의 인덱스 값을 []안에 입력하면 됨
  * 인덱스에 마이너스 기호를 이용하면 맨 뒤에서부터 데이터를 추출할 수 있음

In [16]:
#단일 값 추출

#1부터 9까지의 1차원 ndarray 생성
array1=np.arange(1,10)
print('array1:',array1)

#index는 0부터 시작하므로 array1[2]는 세번째 index 위치의 데이터값을 의미
value=array1[2]
print('value:',value)
print(type(value))

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int64'>


> array1[2] 의 값은 더이상 ndarray 타입이 아니고 ndarray내의 데이터 값을 의미함


In [18]:
#인덱스에 마이너스 값 이용
print('맨뒤의 값 : ', array1[-1],'맨 뒤에서 두번째 값 : ',array1[-2])

맨뒤의 값 :  9 맨 뒤에서 두번째 값 :  8


In [19]:
#인덱스를 이용해 ndarray내의 데이터 값 수정하기
array1[0]=9
array1[8]=0
print('array1:',array1)

array1: [9 2 3 4 5 6 7 8 0]


In [20]:
#다차원 ndarray에서 단일 값 추출
array1d=np.arange(start=1,stop=10)
array2d=array1d.reshape(3,3)
print(array2d)

print('(row=0, col=0) index 가리키는 값 : ',array2d[0,0])
print('(row=0, col=1) index 가리키는 값 : ',array2d[0,1])
print('(row=1, col=0) index 가리키는 값 : ',array2d[1,0])
print('(row=2, col=2) index 가리키는 값 : ',array2d[2,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0) index 가리키는 값 :  1
(row=0, col=1) index 가리키는 값 :  2
(row=1, col=0) index 가리키는 값 :  4
(row=2, col=2) index 가리키는 값 :  9


> array2d[0,1]은 첫번째 로우, 두번째 칼럼 위치의 데이터인 2


  * [row=0, col=1] 인덱싱은 [axis0=0, axis1=1]이 정확한 표현임
    * 일반적인 로우, 칼럼 형식은 넘파이에서는 사용되지 않음
    * 다차원 ndarray의 경우 축(axis)에 따른 연산을 지원함
    * 축 기반의 연산에서 axis가 생략되면 axis 0을 의미함


####(2) 슬라이싱
  * ':' 기호를 이용해 연속한 데이터를 슬라이싱해서 추출
  * ':' 기호 사이에 시작 인덱스와 종료 인덱스를 표시하면 시작 인텍스에서 종료 인덱스 -1의 위치에 있는 데이터의 ndarray 값을 반환
  * 단일 데이터값 추출을 제외하고 슬라이싱, 팬시 인덱싱, 불린 인덱싱으로 추출된 데이터 세트는 모두 ndarray 타입



In [21]:
# 슬라이싱
array1=np.arange(start=1,stop=10)
array3=array1[0:3]
print(array3)
print(type(array3))


[1 2 3]
<class 'numpy.ndarray'>


  * 슬라이싱 기호인 ':'사이의 시작, 종료 인덱스는 생략 가능
    * 시작 인덱스 생략 > 맨 처음 인덱스인 0으로 간주
    * 종료 인덱스 생략 > 맨 마지막 인덱스로 간주
    * ':' 기호 앞 뒤에 시작/종료 인덱스 생략 > 맨 처음/맨 마지막 인덱스로 간주

In [22]:
# ':' 기호 사용하여 시작 인덱스와 종료 인덱스 설정
array1=np.arange(start=1,stop=10)
array4=array1[:3]
print(array4)

array5=array1[3:]
print(array5)

array6=array1[:]
print(array6)


[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [23]:
# 2차원 ndarray에서의 슬라이싱
array1d=np.arange(start=1,stop=10)
array2d=array1d.reshape(3,3)
print('array2d:n',array2d)

print('array2d[0:2,0:2]\n',array2d[0:2,0:2])
print('array2d[1:3,0:3]\n',array2d[1:3,0:3])
print('array2d[1:3,:]\n',array2d[1:3,:])
print('array2d[:,:]\n',array2d[:,:])
print('array2d[:2,1:]\n',array2d[:2,1:])
print('array2d[:2,0]\n',array2d[:2,0])

array2d:n [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2,0:2]
 [[1 2]
 [4 5]]
array2d[1:3,0:3]
 [[4 5 6]
 [7 8 9]]
array2d[1:3,:]
 [[4 5 6]
 [7 8 9]]
array2d[:,:]
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2,1:]
 [[2 3]
 [5 6]]
array2d[:2,0]
 [1 4]


> array[:2,0]과 같이 로우나 칼럼 축 한쪽에만 슬라이싱을 적용하고, 다른 쪽 축에는 단일 값 인덱스를 적용해도 됨

  * 2차원 ndarray에서 뒤에 오는 인덱스를 없애면 1차원 ndarray를 반환 

    (ex.array2d[0]과 같이 2차원에서 뒤에 오는 인덱스를 없애면 로우 축(axis0)의 첫번째 로우 ndarray)를 반환)

In [24]:
# n차원 ndarray에서 마지막 인덱스 지정 생략
print(array2d[0])
print(array2d[1])
print('array2d[0] shape : ', array2d[0].shape,'array2d[1] shape : ',array2d[1].shape)

[1 2 3]
[4 5 6]
array2d[0] shape :  (3,) array2d[1] shape :  (3,)


####(3) 팬시 인덱싱
  * 리스트나 ndarray로 인덱스 집합을 지정하면 해당 위치의 인덱스에 해당하는 ndarray를 반환하는 인덱싱 방식


In [26]:
# 팬시 인덱싱
array1d=np.arange(start=1,stop=10)
array2d=array1d.reshape(3,3)

array3=array2d[[0,1],2]
print('array2d[[0,1],2] => ', array3.tolist())

array4=array2d[[0,1],0:2]
print('array2d[[0:1],0:2] => ',array4.tolist())

array5=array2d[[0,1]]
print('array2d[[0,1]] => ',array5.tolist())

array2d[[0,1],2] =>  [3, 6]
array2d[[0:1],0:2] =>  [[1, 2], [4, 5]]
array2d[[0,1]] =>  [[1, 2, 3], [4, 5, 6]]


> array2d[[0,1],2] 로우 축에 팬시 인덱싱인 [0,1]을, 칼럼 축에는 단일 값 인덱싱 2를 적용

> array2d[[0,1],0:2]는 ((0,0),(0,1)),((1,0),(1,1))이 적용

####(4) 불린 인덱싱
  * 조건 필터링과 검색 가능
  * for loop / if else 문을 간단하게 구현 가능
  *ndarray의 인덱스를 지정하는 []내에 조건문을 그대로 기재하기만 하면 됨

In [27]:
# 불린 인덱싱
array1d=np.arange(start=1,stop=10)
# []안에 array1d>5 Boolean indexing을 적용
array3=array1d[array1d>5]
print('array1d > 5 불린 인덱싱 결과 값 : ', array3)

array1d > 5 불린 인덱싱 결과 값 :  [6 7 8 9]


In [30]:
# 불린 인덱싱의 조건 필터링 과정
array1d>5

boolean_indexes=np.array([False,False,False,False,False,True,True,True,True])
array3=array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과 : ',array3)

indexes=np.array([5,6,7,8])
array4=array1d[indexes]
print('일반 인덱스로 필터링 결과 : ',array4)

불린 인덱스로 필터링 결과 :  [6 7 8 9]
일반 인덱스로 필터링 결과 :  [6 7 8 9]


> 5보다 큰 데이터가 있는 위치는 True 값이, 그렇지 않은 경우는 False 값이 반환됨

> 조건으로 반환된 이 ndarray 객체를 인덱싱을 지정하는 []내에 입력하면 False값은 무시하고 True 값이 있는 위치 인덱스 값으로 자동 변환해 해당하는 인덱스 위치의 데이터만 반환

  * 불린 인덱싱이 동작하는 단계 순차적 도식화

     step1 : array1d>5 와 같이 ndarray의 필터링 조건을 [] 안에 기재

     step2 : False 값은 무시하고 True 값에 해당하는 인덱스값만 저장 (유의해야 할 사항은 True 값 자체인 1을 저장하는 것이 아니라 True 값을 가진 인덱스를 저장한다는 것)
     
     step3 : 저장된 인덱스 데이터 세트로 ndarray 조회 

### 6) 행렬의 정렬 - sort()와 argsort()

####(1) 행렬 정렬
  * np.sort() :  넘파이에서 sort()를 호출하는 방식
    * 원 행렬은 그대로 유지한 채 원 행렬의 정렬된 행렬을 반환
  
  * ndarray.sort() : 행렬 자체에서 sort()를 호출하는 방식
    * 원 행렬 자체를 정렬한 형태로 변환, 반환 값은 None

In [32]:
org_array=np.array([3,1,9,5])
print('원본 행렬 : ',org_array)

#np.sort()로 정렬
sort_array1=np.sort(org_array)
print('np.sort() 호출 후 반환된 정렬 행렬 : ', sort_array1)
print('np.sort() 호출 후 원본 행렬 : ', org_array)

#ndarray.sort()로 정렬
sort_array2=org_array.sort()
print('org_array.sort() 호출 후 반환된 행렬 : ',sort_array2)
print('org_array.sort() 호출 후 원본 행렬 : ',org_array)


원본 행렬 :  [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬 :  [1 3 5 9]
np.sort() 호출 후 원본 행렬 :  [3 1 9 5]
org_array.sort() 호출 후 반환된 행렬 :  None
org_array.sort() 호출 후 원본 행렬 :  [1 3 5 9]


> 원본 행렬에 대해서 np.sort()는 원본 행렬을 변경하지 않고 정렬된 형태로 반환했으며, ndarray.sort()는 원본 행렬 자체를 정렬한 값으로 변환함

  * np.sort()나 ndarray.sort() 모두 깁ㄴ적으로 오름차순으로 행렬 내 원소를 정렬함
  * 내림차순으로 정렬하기 위해서는 [::-1] 을 적용
  

In [33]:
# 내림차순 정렬
sort_array1_desc=np.sort(org_array[::-1])
print('내림차순으로 정렬 : ',sort_array1_desc)

내림차순으로 정렬 :  [1 3 5 9]


  * 행렬이 2차원 이상일 경우에 axis 축 값 설정을 통해 로우방향, 또는 칼럼 방향으로 정렬을 수행할 수 있음

In [36]:
array2d=np.array([[8,12],
                  [7,1]])

sort_array2d_axis0=np.sort(array2d,axis=0)
print('로우방향으로 정렬 : \n' , sort_array2d_axis0) 
#세로 방향으로 정렬, 같은 열에 있는 데이터들끼리 정렬

sort_array2d_axis1=np.sort(array2d,axis=1)
print('칼럼 방향으로 정렬 : \n', sort_array2d_axis1)
#가로 방향으로 정렬, 같은 행에 있는 데이터들끼리 정렬

로우방향으로 정렬 : 
 [[ 7  1]
 [ 8 12]]
칼럼 방향으로 정렬 : 
 [[ 8 12]
 [ 1  7]]


####(2) 정렬된 행렬의 인덱스를 반환하기

  * np.argsort() : 정렬된 행렬의 원본 행렬 인덱스를 ndarray 형으로 반환

    * 원본 행렬이 정렬되었을 때 기존 원본 행렬의 원소에 대한 인덱스를 피룡로 할 때 사용


In [37]:
org_array=np.array([3,1,9,5])
sort_indices=np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스 : ', sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스 :  [1 0 3 2]


  * 내림차순으로 정렬 시에 원본 행렬의 인덱스를 구하는 것도 np.argsort()[::-1]과 같이 적용하면 됨
  

In [39]:
# np.argsort()[::-1]
org_array=np.array([3,1,9,5])
sort_indices_desc=np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스 : ', sort_indices_desc)


행렬 내림차순 정렬 시 원본 행렬의 인덱스 :  [2 3 0 1]



  * 넘파이의 ndarray는  RDBMS 의 TABLE 칼럼이나 뒤에 소개할 판다스 DataFrame 칼럼과 같은 메타 데이터를 가질 수 없음. 따라서 실제 값과 그 값이 뜻하는 메타 데이터를 별도의 ndarray로 각각 가져야만 함
    * ex. 학생의 이름과 시험 성적을 ndarray 형태의 데이터로 가지려면 학생 ndarray와 성적 ndarray를 각각 가져야 함
    * 이 때 시험 성적순으로 학생 이름을 출력하고자 한다면 np.argsort(성적)을 이용해 반환된 인덱스를 학생 ndarray에 팬시 인덱스로 적용해 추출할 수 있음.

In [43]:
import numpy as np

name_array=np.array(['John','Mike','Sarah','Kate','Samuel'])
score_array=np.array([78,95,84,98,88])

sort_indices_asc=np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스 : ',sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력 : ', name_array[sort_indices_asc])

성적 오름차순 정렬 시 score_array의 인덱스 :  [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력 :  ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


###7) 선형대수 연산 - 행렬 내적과 전치 행렬 구하기

####(1) 행렬 내적(행렬 곱)
  * 행렬 내적 = 행렬 곱
  * np.dot()
  * 행렬의 내적은 왼쪽 행렬의 행과 오른쪽 행렬의 열의 원소들을 순차적으로 곱한 뒤 그 결과를 모두 더한 값
  * 왼쪽 행렬의 열 개수와 오른쪽 행렬의 행 개수가 동일해야 내적 연산이 가능함
  

In [44]:
# 행렬 내적
A=np.array([[1,2,3],
            [4,5,6]])
B=np.array([[7,8],
            [9,10],
            [11,12]])

dot_product=np.dot(A,B)
print('행렬 내적 결과 : \n', dot_product)


행렬 내적 결과 : 
 [[ 58  64]
 [139 154]]


####(2) 전치 행렬
  * 원 행렬에서 행과 열 위치를 교환한 원소로 구성한 행렬
  * transpose()
  

In [46]:
# 전치 행렬
A=np.array([[1,2],
            [3,4]])
transpose_mat=np.transpose(A)
print('A의 전치행렬 : \n',transpose_mat)

A의 전치행렬 : 
 [[1 3]
 [2 4]]
