<a href="https://colab.research.google.com/github/seodalzzz/ESAA/blob/Python_Machine_Learning/Pytorch_CHAP2_Basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**CHAP2 파이토치 기초**

---
https://wikidocs.net/57168
---




##1.파이토치 패키지의 기본 구성

###1) torch
  * 메인 네임스페이스
  * 텐서 등의 다양한 수학 함수 포함
  * Numpy와 유사한 구조를 가짐

### 2) torch.autograd
  * 자동 미분을 위한 함수들이 포함됨
  * 자동 미분의 on/off 를 제어하는 콘텍스트 매니저(enable_grad/no_grad)나 자체 미분 가능 함수를 정의할 때 사용하는 기반 클래스인 'Function'등이 포함 됨

###3) torch.nn
  * 신경망을 구축하기 위한 다양한 데이터구조나 레이어 등이 정의됨
  * 레이어 (RNN, LSTM 등), 활성화 함수 (ReLU 등), Loss Function (MSE 등)

###4) torch.optim
  * SGD를 중심으로 한 파라미터 최적화 알고리즘 구현

###5) torch.utils.data
  * SGD의 반복 연산을 실행할 때 사용하는 미니 배치용 유틸리티 함수가 포함됨

###6) torch.onnx
  * ONNX의 포맷으로 모델을 export할 때 사용
  * ONNX : 서로 다른 딥 러닝 프레임워크 간에 모델을 공유할 때 사용하는 포맷

##2.텐서 조작하기
  * 벡터,  행렬, 텐서의 개념에 대해 이해
  * Numpy와 파이토치로 벡터, 행렬, 텐서를 다루는 방법에 대해 이해

###1) 벡터, 행렬 그리고 텐서
  * 스칼라 : 차원이 없는 값
  * 벡터 : 1차원으로 구성된 값
  * 행렬 : 2차원으로 구성된 값
  * 텐서 : 3차원으로 구성된 값
  * 데이터 사이언스 분야 한정으로 3차원 이상의 텐서는 다차원 행렬 또는 배열로 간주 가능

####(1) Pytorch Tensor Shape Convention
  * 2D Tensor
    * |t|=(Batch Size, dim)
  * 3D Tensor - CV
    * |t|=(batch size, width, height)
  * 3D Tensor - NLP
    * |t|=(batch size, length, dim) = (batch size, 문장 길이, 단어 벡터의 차원)


###2)넘파이로 텐서 만들기 (벡터와 행렬 만들기)



* 넘파이 부분은 생략

###3) 파이토치 텐서 선언하기(PyTorch Tensor Allocation)

In [4]:
import torch

####(1) 1D with PyTorch

In [5]:
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [6]:
print(t.dim())  # rank. 즉, 차원
print(t.shape)  # shape
print(t.size()) # shape

1
torch.Size([7])
torch.Size([7])


In [7]:
print(t[0], t[1], t[-1])  # 인덱스로 접근
print(t[2:5], t[4:-1])    # 슬라이싱
print(t[:2], t[3:])       # 슬라이싱

tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


####(2) 2D with Torch

In [8]:
t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]
                      ])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [9]:
print(t.dim())  # rank. 즉, 차원
print(t.size()) # shape

2
torch.Size([4, 3])


In [10]:
print(t[:, 1]) # 첫번째 차원을 전체 선택한 상황에서 두번째 차원의 첫번째 것만 가져온다.
print(t[:, 1].size()) # ↑ 위의 경우의 크기

tensor([ 2.,  5.,  8., 11.])
torch.Size([4])


In [11]:
print(t[:, :-1]) # 첫번째 차원을 전체 선택한 상황에서 두번째 차원에서는 맨 마지막에서 첫번째를 제외하고 다 가져온다.

tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


####(3) 브로드캐스팅
  * 크기가 다른 행렬 또는 텐서에 대해서 사칙 연산을 수행할 필요가 있는 경우 자동으로 크기를 맞춰서 연산을 수행하도록 함

In [13]:
#크기가 같은 경우
m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2, 2]])
print(m1 + m2)

tensor([[5., 5.]])


In [14]:
#크기가 다른 경우
# Vector + scalar
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3]) # [3] -> [3, 3]
print(m1 + m2)

tensor([[4., 5.]])


* m2의 크기를 (1,2)로 변경하여 연산을 수행

In [15]:
# 벡터 간 연산에서 브로드캐스팅이 적용되는 경우
# 2 x 1 Vector + 1 x 2 Vector
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3], [4]])
print(m1 + m2)

tensor([[4., 5.],
        [5., 6.]])


* 브로드캐스팅은 편리하지만 자동으로 실행되므로 주의해서 사용해야 함

###(4) 자주 사용되는 기능들

##### -1- 행렬 곱셈(.matmul)과 곱셈(.mul)의 차이

* 파이토치 텐서의 행렬 곱셈 - matmul()

In [16]:
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1.matmul(m2)) # 2 x 1

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])


* element-wise 곱셈 - *,mul()
  * 서로 다른 크기의 행렬이 브로드캐스팅 된 후에 element-wize 곱셈이 수행됨

In [17]:
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape) # 2 x 2
print('Shape of Matrix 2: ', m2.shape) # 2 x 1
print(m1 * m2) # 2 x 2
print(m1.mul(m2))

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


##### -2- 평균

In [18]:
#1차원 벡터
t = torch.FloatTensor([1, 2])
print(t.mean())

tensor(1.5000)


In [19]:
#2차원 행렬
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [20]:
print(t.mean())

tensor(2.5000)


* dim을 인자로 주는 경우 해당 차원을 없앤다는 의미
  * dim=0 : 행 => 행을 지우고 열의 평균을 계산

In [21]:
# dim 을 인자로 주는 경우
print(t.mean(dim=0))

tensor([2., 3.])


In [22]:
print(t.mean(dim=1))

tensor([1.5000, 3.5000])


In [23]:
#dim=-1 => 마지막 차원을 제거
print(t.mean(dim=-1))

tensor([1.5000, 3.5000])


#####-3- 덧셈

In [24]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [25]:
print(t.sum()) # 단순히 원소 전체의 덧셈을 수행
print(t.sum(dim=0)) # 행을 제거
print(t.sum(dim=1)) # 열을 제거
print(t.sum(dim=-1)) # 열을 제거

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


#####-4- Max와 ArgMax

In [26]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [27]:
print(t.max()) # Returns one value: max

tensor(4.)


* max에 dim 인자를 주면 argmax도 함께 리턴

In [28]:
print(t.max(dim=0)) # Returns two values: max and argmax

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))


* max 또는 argmax만 리턴받고 싶다면 리턴값에도 인덱스를 부여
  * 인덱스 0 : max
  * 인덱스 1 : argmax

In [29]:
print('Max: ', t.max(dim=0)[0])
print('Argmax: ', t.max(dim=0)[1])

Max:  tensor([3., 4.])
Argmax:  tensor([1, 1])


In [30]:
print(t.max(dim=1))
print(t.max(dim=-1))

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))


### 4) 뷰(View) - 원소의 수를 유지하면서 텐서의 크기 변경
  * 넘파이에서의 reshape와 같은 역할
  * 텐서의 크기(Shape)를 변경해주는 역할

In [31]:
t = np.array([[[0, 1, 2],
               [3, 4, 5]],
              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)

In [32]:
print(ft.shape)

torch.Size([2, 2, 3])


#### (1) 3차원 텐서에서 2차원 텐서로 변경

In [33]:
print(ft.view([-1, 3])) # ft라는 텐서를 (?, 3)의 크기로 변경
print(ft.view([-1, 3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


* view([-1,3])
  * -1 : 첫번째 차원은 사용자가 잘 모르겠으니 파이토치에 맡기겠다
  * 3 : 두번째 차원의 길이는 3을 가지도록 하라
  * (2,2,3)->(2x2,3)->(4,3)

* view는 기본적으로 변경 전과 변경 후의 텐서 안의 원소의 개수가 유지되어야 함
* 파이토치의 view는 사이즈가 -1로 설정되면 다른 차원으로부터 해당 값을 유추

####(2) 3차원 텐서의 크기 변경
  * 3차원 텐서에서 3차원 텐서로 차원은 유지하되, 크기를 바꾸는 작업

In [34]:
print(ft.view([-1, 1, 3]))
print(ft.view([-1, 1, 3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


###5) 스퀴즈 - 1인 차원을 제거

In [35]:
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


* (3x1) 크기를 가지는 텐서 -> 두번째 차원이 1이므로 squeeze를 사용하면 (3,)의 크기를 가지는 텐서로 변경됨

In [36]:
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


###6) 언스퀴즈 - 특정 ㅜ이치에 1인 차원을 추가

In [37]:
ft = torch.Tensor([0, 1, 2])
print(ft.shape)

torch.Size([3])


In [38]:
print(ft.unsqueeze(0)) # 인덱스가 0부터 시작하므로 0은 첫번째 차원을 의미한다.
print(ft.unsqueeze(0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


* 언스퀴즈와 view가 동일한 결과가 됨

In [39]:
print(ft.view(1, -1))
print(ft.view(1, -1).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


* view(), squeeze(), unsqueeze()는 텐서의 우너소 수를 그대로 유지하면서 모양과 차원을 조절함



### 7) 타입 캐스팅
* 자료형 변환

In [42]:
# long 타입의 텐서 선언
lt = torch.LongTensor([1, 2, 3, 4])
print(lt)

tensor([1, 2, 3, 4])


In [43]:
#float 형으로 변환
print(lt.float())

tensor([1., 2., 3., 4.])


In [44]:
# byte 타입의 텐서 선언
bt = torch.ByteTensor([True, False, False, True])
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


In [45]:
#long 형 / float 형 텐서로 변환
print(bt.long())
print(bt.float())

tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


### 8) 연결하기
  * 두 텐서를 연결

In [46]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])

* torch.cat
  * 어느 차원을 늘릴 것인지를 인자로 줄 수 있음
  * ex. dim=0 은 첫번째 차원을 늘리는 것

In [47]:
print(torch.cat([x, y], dim=0))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])


  * 두 개의 (2x2) -> (4x2)

In [48]:
print(torch.cat([x, y], dim=1))

tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


###9) 스택킹
  * 영어로 쌓는다는 의미

In [49]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

In [50]:
print(torch.stack([x, y, z]))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [51]:
# 동일한 작업
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


* 스택킹에 dim 인자 주기

In [53]:
# dim=1 : 두번째 차원이 증가하도록 쌓으라는 의미
print(torch.stack([x, y, z], dim=1))

tensor([[1., 2., 3.],
        [4., 5., 6.]])


###10) ones_like와 zeros_like - 0으로 채워진 텐서와 1로 채워진 텐서

In [54]:
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [55]:
print(torch.ones_like(x)) # 입력 텐서와 크기를 동일하게 하면서 값을 1로 채우기

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [56]:
print(torch.zeros_like(x)) # 입력 텐서와 크기를 동일하게 하면서 값을 0으로 채우기

tensor([[0., 0., 0.],
        [0., 0., 0.]])


###11) In-place Operation (덮어쓰기 연산)

In [57]:
x = torch.FloatTensor([[1, 2], [3, 4]])

In [58]:
print(x.mul(2.)) # 곱하기 2를 수행한 결과를 출력
print(x) # 기존의 값 출력

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])


* 연산 뒤에 _를 붙이면 기존의 값을 덮어씀

In [59]:
print(x.mul_(2.))  # 곱하기 2를 수행한 결과를 변수 x에 값을 저장하면서 결과를 출력
print(x) # 기존의 값 출력

tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])
